const accountselector = {		
	"Enrollmentsettings": "form > div:nth-of-type(1) > div:nth-of-type(1) > div:nth-of-type(1) > div",
	"SelectLanguage": "html > body > div > div > div > form > div:nth-of-type(1) > div:nth-of-type(1) > div:nth-of-type(2) > span:nth-of-type(1)",
	"Checklanguages": '[name="language"]',
	"Yourenrollerid": 'div:nth-of-type(1) > div:nth-of-type(3) > label',
	"DontknowrefferalID": "div:nth-of-type(1) > div:nth-of-type(1) > div:nth-of-type(5)",
	"DonthaverefferalID": "div:nth-of-type(1) > div:nth-of-type(6) > div",
	"AboutYou":"form > div:nth-of-type(1) > div:nth-of-type(2) > div:nth-of-type(1) > div",
	"firstname": "div:nth-of-type(2) > div:nth-of-type(2) > label",
	"lastname": "div:nth-of-type(2) > div:nth-of-type(3) > label",
	"birthdate": "div:nth-of-type(2) > div:nth-of-type(4) > label",
	"ssn": "div:nth-of-type(2) > div:nth-of-type(7) > label",
	"gender":"div:nth-of-type(8) > span:nth-of-type(1)",
	"martialstatus":"div:nth-of-type(9) > span:nth-of-type(1)",
	"emailcommunication":'[name="recieveEmail"]',

	"noenrollersponsor": '[name="noEnrollerSponsorId"]',
	"enroller":'[name="enrollerName"]',
	

	"Enroller": '[name="enrollerId"]',
	"Sponsor": '[name="sponsorId"]',
	"FirstName": 'input[name=firstName][autocomplete=none]',
	"LastName": 'input[name="lastName"][autocomplete=none]',
	"DOB": 'input[name="dob"][autocomplete=none]',
	"Phone": 'input[name="phoneNumber"][autocomplete=none]',
	"Email": 'input[name="email"][autocomplete=none]',
	"TaxID": 'input[name="ssn"][autocomplete=none]',
	"Gender": '[name="gender"]',
	"Martial": '[name="maritalStatus"]',
	"CoApplicant": '.fullName > div >',
	"Confirmpassword": '[name="confirmPassword"]',
	"Showpassword" : '[name="showPassword"]',
	"AccountContinue": "div:nth-of-type(2) > button",

	"Error" : "form > div > div > div > div > span",

	"accountsetup" : "#app > div > div > div:nth-child(3) > div",
	"labels": '*label',
	"sponsor":'[name="sponsor"]',
	"firstname": "[name='firstName']",
	"lastname": "[name='lastName']",
	"phone": "[name='phoneNumber']",
	"email": "[name='emailAddress']",
	"password": '[name="password"]',
	"termsandconditions" : '[type="checkbox"]',
	"freemembership" : "#checkMarks > div > div:nth-child(1) > div",
	"enjoywholesalepricing" : "#checkMarks > div > div:nth-child(2) > div",
	"earnproductcredit" : "#checkMarks > div > div:nth-child(3) > div",
	"freeshippingonautorefill" : "#checkMarks > div > div:nth-child(4) > div",
	"iagreetotheunicitymember" : "[rel='noopener noreferrer']",
	"signup" : "[aria-label='Delete'] > span:nth-child(1)",
	"countryname" : "[name='countryName']",
	"country" : "[for='countryName']",
}

export default accountselector	